### PR TITLE
[1.14] Hard delete calendar items on synchronization of imported calendar

### PR DESCRIPTION
**Pull request by yurabakhtin**
Issue: https://github.com/humhub/team_tasks/issues/284

### CODE REVIEW

**Review by luke- — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look into the failing tests?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please take a look into the failing tests?

Strange errors, because locally all tests work without any error.

If we look at the first error:

```
1) RecurrenceExpandTest: Expand single
 Test  codeception/unit/RecurrenceExpandTest.php:testExpandSingle

  [yii\base\ErrorException] Undefined offset: 0  

#1  /home/runner/work/external_calendar/external_calendar/protected/modules/external_calendar/tests/codeception/unit/RecurrenceExpandTest.php:28
```

on the lines we have a code:

```php
$externalCalendar = $this->initCalendar('@external_calendar/tests/codeception/data/recurrence1.ics');
$recurrenceEvent = $externalCalendar->getRecurringEventRoots()[0];
```

it seems the `$externalCalendar` is empty array, however on debug I see the var contains 1 item as object `humhub\modules\external_calendar\models\ExternalCalendarEntry`.
Maybe the file `@external_calendar/tests/codeception/data/recurrence1.ics` cannot be readable by some reason.

**Comment by luke-** [comment]
@yurabakhtin Hmm, thats strange. Should we merge this PR and release the module?
I would then create an issue to fix the tests and then we look at this again at a later date.

**Comment by yurabakhtin** [comment]
@luke- 

> Hmm, thats strange. Should we merge this PR and release the module?

Yes, very strange, but I have run the tests again locally on `master` and `develop` and they all work without errors, so I think it can be merged.

external_calendar_tests

> I would then create an issue to fix the tests and then we look at this again at a later date.

I see tests for `develop` are executed by cron so we will see errors in this issue https://github.com/humhub/team_tasks/issues/284

**Pull request merged**
